export const GET_COCKTAIL_BY_ID_REQUEST = "GET_COCKTAIL_BY_ID_REQUEST";
export const GET_COCKTAIL_BY_ID_SUCCESS = "GET_COCKTAIL_BY_ID_SUCCESS";
export const GET_COCKTAIL_BY_ID_FAIL = "GET_COCKTAIL_BY_ID_FAIL";
// export const GET_COCKTAIL_BY_ID_REQUEST = "GET_COCKTAIL_BY_ID_REQUEST";
// export const GET_COCKTAIL_BY_ID_SUCCESS = "GET_COCKTAIL_BY_ID_SUCCESS";
// export const GET_COCKTAIL_BY_ID_FAIL = "GET_COCKTAIL_BY_ID_FAIL";
