export const GET_COCKTAILS_LIST_REQUEST = "GET_COCKTAILS_LIST_REQUEST";
export const GET_COCKTAILS_LIST_SUCCESS = "GET_COCKTAILS_LIST_SUCCESS";
export const GET_COCKTAILS_LIST_FAIL = "GET_COCKTAILS_LIST_FAIL";
export const CHANGE_FILTER = "CHANGE_FILTER";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const DELETE_FAVORITE = "DELETE_FAVORITE";
